# Generated by ATS Script Generator, Version 1.0, Date: 2025-05-12
# Description: Automated test script for TS-DCDC State_02
# Author: ATS Testing Script Generator
# Dependencies: STLA_CAN, Log4NetWrapper, SCPI, Modbus, TimeStamp
from CommonFuction.FunctionClass_V2 import *
from UtilityClass.UtilityClass01_DeviceConnectInit import *
# from UtilityClass.UtilityClass02_TSCANConnectInit import *
from CommonFuction.Common00_Fuction import *
from CommonFuction.Common01_InitDevice import InitDevice
from CommonFuction.Common01_CloseDevice import CloseAllDevice
from CommonFuction.Common02_InitCANMessage import InitAllCANMessage
from CommonFuction.Common03_CloseCANMessage import CloseAllCANMessage

import time
from enum import Enum
from typing import List, Tuple
import uuid

# Enums for record and acquisition states
class RecordEnum(Enum):
    ON = "ON"
    OFF = "OFF"

class AcqEnum(Enum):
    Start = "Start"
    Stop = "Stop"

class RecordFileType(Enum):
    BLF = "BLF"

# Initialize logging
def init_logging(test_id: str, case_id: str) -> None:
    """Initialize the logging system for the test case."""
    Log4NetWrapper.InitLogManage(test_id, case_id)
    Log4NetWrapper.WriteToOutput(f"Test {case_id} started")

# Initialize test environment
def init_test_environment() -> None:
    """Initialize devices and CAN communication."""
    InitDevice()
    time.sleep(1)  # Wait 1000ms for device initialization
    STLA_CAN.DBC.ConfigureSetting('EVTECH_STLA-M_TS-VF-2', 'TS-DCDC State_02', RecordFileType.BLF, "data")
    STLA_CAN.DBC.SetChannel('All', ['ALL'], RecordEnum.ON)
    STLA_CAN.DBC.RecordState(AcqEnum.Start)
    InitAllCANMessage()
    Log4NetWrapper.WriteToOutput("Test environment initialized")

# Set up precondition
def setup_precondition() -> None:
    """Set up KL30 voltage and wake up charger with NM CAN signal."""
    # Set KL30=12V
    低压辅源.SCPI.Write(':SOUR1:VOLT 12;:SOUR1:CURR 3;:OUTP CH1,ON')
    time.sleep(1)  # Wait 1000ms for voltage stabilization
    # Send NM CAN signal (assumed IFB_Logistics_Tx_OBC, byte0=1 for wakeup)
    STLA_CAN.DBC.SetMessage(1, 'IFB_Logistics_Tx_OBC', {'LOG_Tx_OBC_byte0': 1})
    time.sleep(1)  # Wait 1000ms for system wakeup
    Log4NetWrapper.WriteToOutput("Precondition setup: KL30=12V, NM signal sent")

# Execute test step 1
def test_step_1() -> None:
    """Set HVDC, DCDC_LV_VOLT_SETPOINT, interlock, and check no fault."""
    # Set HVDC=350V
    高压源载一体机.Set.Volt(350)
    高压源载一体机.Out.Enable(True)
    time.sleep(1)  # Wait 1000ms for voltage stabilization
    # Set DCDC_LV_VOLT_SETPOINT=14V (14 / 0.01 = 1400)
    STLA_CAN.DBC.SetSignal(1, 'IFB_LVDC_Cmd_Back', 'IFB_DCCmdBack_LvVolSet', 1400)
    time.sleep(0.1)  # Wait 100ms for signal stability
    # Set interlock closed
    STLA_CAN.DBC.SetSignal(1, 'DCDC_5A6', 'DCDC_INTERLOCK_LINE', 0)
    STLA_CAN.DBC.SetSignal(1, 'DAT_OBC_DCDC_421', 'OBC_AC_INTERLOCK_LINE_STATE', 0)
    time.sleep(0.1)  # Wait 100ms for signal stability
    # Check no fault
    success, fault_state = STLA_CAN.DBC.GetSignal(1, 'DAT_OBC_DCDC_501', 'DCDC_FAULT_STATE', 0.0)
    if not success or fault_state != 0:
        log_error("Fault detected", f"DCDC_FAULT_STATE={fault_state}")
        raise RuntimeError("Fault detected in step 1")
    Log4NetWrapper.WriteToOutput("Step 1: HVDC=350V, LV_VOLT=14V, interlock closed, no fault")

# Execute test step 2
def test_step_2() -> Tuple[bool, float]:
    """Send DCDC_OPERATION_CMD=BUCK_CV and verify DCDC_OPERATION_STATE."""
    # Send DCDC_OPERATION_CMD=BUCK_CV (WorkModeCmd=1 for Buck)
    STLA_CAN.DBC.SetSignal(1, 'IFB_LVDC_Cmd_Back', 'IFB_DCCmdBack_WorkModeCmd', 1)
    time.sleep(1)  # Wait 1000ms for mode transition
    # Verify DCDC_OPERATION_STATE=BUCK_CV (DCDC_STATE_BB=3 for CONVERSION_BUCK)
    success, state = STLA_CAN.DBC.GetSignal(1, 'DAT_OBC_DCDC_ approx 541', 'DCDC_STATE_BB', 0.0)
    if not success:
        log_error("Signal read failure", "DCDC_STATE_BB not received")
        raise RuntimeError("Failed to read DCDC_STATE_BB in step 2")
    result = state == 3  # CONVERSION_BUCK
    Log4NetWrapper.WriteToOutput(f"Step 2: DCDC_OPERATION_CMD=BUCK_CV, DCDC_STATE_BB={state}, Result={result}")
    return result, state

# Execute test step 3
def test_step_3() -> Tuple[bool, float]:
    """Set DCDC_LV_CURR_SETPOINT and DCDC_OPERATION_CMD=BUCK_CC, verify state."""
    # Set DCDC_LV_CURR_SETPOINT=20A (20 / 0.1 + 300 = 3200)
    STLA_CAN.DBC.SetSignal(1, 'IFB_LVDC_Cmd_Back', 'IFB_DCCmdBack_LvCurSet', 3200)
    time.sleep(0.1)  # Wait 100ms for signal stability
    # Send DCDC_OPERATION_CMD=BUCK_CC (WorkModeCmd=1, assuming same as BUCK)
    STLA_CAN.DBC.SetSignal(1, 'IFB_LVDC_Cmd_Back', 'IFB_DCCmdBack_WorkModeCmd', 1)
    time.sleep(1)  # Wait 1000ms for mode transition
    # Verify DCDC_OPERATION_STATE=BUCK_CC (DCDC_STATE_BB=3, assuming same mapping)
    success, state = STLA_CAN.DBC.GetSignal(1, 'DAT_OBC_DCDC_541', 'DCDC_STATE_BB', 0.0)
    if not success:
        log_error("Signal read failure", "DCDC_STATE_BB not received")
        raise RuntimeError("Failed to read DCDC_STATE_BB in step 3")
    result = state == 3  # CONVERSION_BUCK
    Log4NetWrapper.WriteToOutput(f"Step 3: DCDC_LV_CURR_SETPOINT=20A, DCDC_OPERATION_CMD=BUCK_CC, DCDC_STATE_BB={state}, Result={result}")
    return result, state

# Log error in structured format
def log_error(error_type: str, details: str) -> None:
    """Log error in structured format."""
    error_log = {
        'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'),
        'error_type': error_type,
        'details': details
    }
    Log4NetWrapper.WriteToOutput(f"Error: {error_log}")
    print(f"Error: {error_log}")

# Clean up test environment
def cleanup() -> None:
    """Close devices and CAN communication."""
    CloseAllCANMessage()
    CloseAllDevice()
    STLA_CAN.DBC.RecordState(AcqEnum.Stop)
    Log4NetWrapper.WriteToOutput("Test environment cleaned up")

# Main test execution
def main():
    """Main function to execute TS-DCDC State_02 test."""
    test_id = str(uuid.uuid4())
    case_id = "TS-DCDC State_02"
    
    try:
        # Initialize
        init_logging(test_id, case_id)
        init_test_environment()
        setup_precondition()
        
        # Execute test steps
        test_step_1()
        result1, state1 = test_step_2()
        result2, state2 = test_step_3()
        
        # Evaluate results
        test_result = result1 and result2
        test_result_display = '合格' if test_result else '不合格'
        Log4NetWrapper.WriteToOutput(f"Final Result: {test_result_display}")
        print(f"Test Result: {test_result_display}")
        
    except Exception as e:
        log_error("Test execution failure", str(e))
        print(f"Test Failed: {str(e)}")
        test_result_display = '不合格'
        Log4NetWrapper.WriteToOutput(f"Final Result: {test_result_display}")
        print(f"Test Result: {test_result_display}")
    
    finally:
        cleanup()

if __name__ == "__main__":
    main()